core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

project_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from project_manager import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path

from . import views

app_name = 'task'

urlpatterns = [
    path('add/', views.add_task, name='add'),
    path('<uuid:pk>/', views.detail, name='detail'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete_todolist/', views.delete, name='delete_todolist'),
]

task/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from project.models import Project
from todolist.models import ToDoList

User = get_user_model()


class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks')
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE, related_name='tasks')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(
        choices=(
            ('open', 'Open'),
            ('in_progress', 'In Progress'),
            ('done', 'Done'),
        )
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name

task/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from project.models import Project
from task.models import Task
from todolist.models import ToDoList


@login_required()
def add_task(request, project_id, todolist_id):
    project = get_object_or_404(Project, id=project_id)
    todolist = ToDoList.objects.filter(project=project).get(pk=todolist_id)

    if request.method == 'POST':
        if request.user != project.owner and request.user not in project.collaborators.all():
            messages.error(request, "You do not have permission to access this project.")
            return redirect('project:project_detail', pk=project.id)

        name = request.POST.get('name')
        description = request.POST.get('description')
        status = request.POST.get('status')
        created_by = request.user

        Task.objects.create(
            project=project, todolist=todolist, name=name, description=description,
            status=status, created_by=created_by
        )

        messages.success(request, 'Task added successfully')

        return redirect('todolist:todolist', project.id, todolist.id)

    return render(request, 'task/add_task.html', {'project': project, 'todolist': todolist})


@login_required()
def detail(request, project_id, todolist_id, pk):
    project = Project.objects.get(pk=project_id)
    todolist = ToDoList.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project, todolist=todolist).get(pk=pk)

    if request.user != project.owner and request.user not in project.collaborators.all():
        messages.error(request, "You do not have permission to access this project.")
        return redirect('project:project_detail', pk=project.id)

    return render(request, 'task/detail.html', {'project': project, 'todolist': todolist, 'task': task})


@login_required()
def edit(request, project_id, todolist_id, pk):
    project = Project.objects.get(pk=project_id)
    todolist = ToDoList.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project, todolist=todolist).get(pk=pk)

    if request.method == 'POST':
        if request.user != project.owner and request.user not in project.collaborators.all():
            messages.error(request, "You do not have permission to edit this task.")
            return redirect('project:project_detail', pk=project.id)

        name = request.POST.get('name')
        description = request.POST.get('description')
        status = request.POST.get('status')

        if name:
            task.name = name

        task.description = description
        task.status = status
        task.save()

    return redirect('task:detail', project.id, todolist.id, task.id)


@login_required()
def delete(request, project_id, todolist_id, pk):
    project = Project.objects.get(pk=project_id)
    todolist = ToDoList.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project, todolist=todolist).get(pk=pk)

    if request.user != task.created_by:
        messages.error(request, "You do not have permission to delete this task.")
        return redirect('todolist:todolist', project.id, todolist.id)

    task.delete()
    messages.success(request, 'Task deleted successfully')

    return redirect('todolist:todolist', project.id, todolist.id)

task/templates/task/detail.html
{% extends 'core/base.html' %}
{% block title %}Todolist details{% endblock %}

{% block content %}

    <h1 class="mb-6 text-3xl">{{ task.name }}</h1>
    <p class="mb-8 text-lg">{{ task.description }}</p>
    <p class="mb-8 text-lg">{{ task.get_status_display }}</p>
    <div class="mb-8 flex flex-wrap justify-start gap-4">

        <!-- Modal Edit task --->
        <button data-modal-target="crud-modal-edit-task" data-modal-toggle="crud-modal-edit-task"
                class="block text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-blue-500 hover:to-blue-900 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 w-full sm:w-auto"
                type="button">
            Edit
        </button>
        <div id="crud-modal-edit-task" tabindex="-1" aria-hidden="true"
             class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
            <div class="relative p-4 w-full max-w-md max-h-full">
                <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                    <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                            Edit task "{{ task.name }}"
                        </h3>
                        <button type="button"
                                class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                                data-modal-toggle="crud-modal-edit-task">
                            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                                 viewBox="0 0 14 14">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2"
                                      d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                            </svg>
                            <span class="sr-only">Close modal</span>
                        </button>
                    </div>
                    <form class="p-4 md:p-5" method="post"
                          action="{% url 'task:edit' task.todolist.project.id task.todolist_id task.id %}">
                        {% csrf_token %}
                        <div class="grid gap-4 mb-4 grid-cols-2">
                            <div class="col-span-2">
                                <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
                                <input type="text" name="name" id="name"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                                       value="{{ task.name }}">
                            </div>
                            <div class="col-span-2 sm:col-span-1">
                                <label for="status"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Status</label>
                                <select id="status" name="status"
                                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                                    <option value="open {% if task.status == 'open' %}selected{% endif %}">
                                        Open
                                    </option>
                                    <option value="in_progress"
                                            {% if task.status == 'in_progress' %}selected{% endif %}>
                                        In Progress
                                    </option>
                                    <option value="done" {% if task.status == 'done' %}selected{% endif %}>
                                        Done
                                    </option>
                                </select>
                            </div>
                            <div class="col-span-2">
                                <label for="description"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                    Description</label>
                                <textarea id="description" rows="4" name="description"
                                          class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                >{{ task.description }}</textarea>
                            </div>
                        </div>
                        <button type="submit"
                                class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            Save
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <!-- Modal Delete task -->
        {% if request.user == task.created_by %}
            <button data-modal-target="modal-delete-task" data-modal-toggle="modal-delete-task"
                    class="block text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 w-full sm:w-auto"
                    type="button">
                Delete
            </button>

            <div id="modal-delete-task" tabindex="-1"
                 class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative p-4 w-full max-w-md max-h-full">
                    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                        <button type="button"
                                class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                                data-modal-toggle="modal-delete-task">
                            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                                 viewBox="0 0 14 14">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2"
                                      d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                            </svg>
                            <span class="sr-only">Close modal</span>
                        </button>
                        <div class="p-4 md:p-5 text-center">
                            <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2"
                                      d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"></path>
                            </svg>
                            <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Are you sure you want
                                to
                                delete {{ task.name }}?</h3>
                            <a data-modal-toggle="modal-delete-task" type="button"
                               href="{% url 'task:delete' task.todolist.project.id task.todolist_id task.id %}"
                               class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center">
                                Yes, I'm sure
                            </a>

                            <a data-modal-toggle="modal-delete-task"
                               class="py-2.5 px-5 ms-3 text-sm cursor-pointer font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
                                No, cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        <a href="{% url 'todolist:todolist' project.id todolist.id %}"
           class="py-4 px-8 bg-gray-500 hover:bg-gray-800 text-white rounded-lg inline-block w-full sm:w-auto text-center">
            Back
        </a>
    </div>

    <div class="mt-6 mb-4 md:mb-8 lg:mb-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 lg:mb-2">
    </div>
{% endblock %}