core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

project_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from project_manager import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete_todolist/', views.delete, name='delete_todolist'),
]

todolist/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from project.models import Project

User = get_user_model()


class ToDoList(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='todolists')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_todolists')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name

todolist/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from project.models import Project
from .models import ToDoList


@login_required()
def todolist(request, project_id, pk):
    project = Project.objects.filter(pk=project_id).first()
    todolist = ToDoList.objects.filter(project=project).get(pk=pk)

    if request.user == project.owner or request.user in project.collaborators.all():
        return render(request, 'todolist/todolist.html', {'project': project, 'todolist': todolist})


@login_required
def add(request, project_id):
    project = Project.objects.get(pk=project_id)

    if request.method == 'POST':

        if request.user != project.owner and request.user not in project.collaborators.all():
            messages.error(request, "You do not have permission to add a new To-Do List.")
            return redirect('project:project_detail', pk=project_id)

        name = request.POST.get('name')
        description = request.POST.get('description')

        if name:
            ToDoList.objects.create(name=name, description=description, created_by=request.user,
                                    project_id=project_id)
            return redirect('project:project_detail', pk=project_id)

    return redirect('project:project_detail', pk=project_id)


@login_required()
def edit(request, project_id, pk):
    project = Project.objects.get(pk=project_id)
    todolist = ToDoList.objects.filter(project=project).get(pk=pk)

    if request.method == 'POST':
        if request.user != project.owner and request.user not in project.collaborators.all():
            messages.error(request, "You do not have permission to edit this To-Do List.")

            return redirect('project:project_detail', pk=project_id)

        name = request.POST.get('name')
        description = request.POST.get('description')

        if name:
            todolist.name = name
            todolist.description = description
            todolist.save()
            return redirect('todolist:todolist', project_id=project_id, pk=pk)

    return render(request, 'todolist/edit.html', {'project': project, 'todolist': todolist})


@login_required()
def delete(request, project_id, pk):
    project = Project.objects.get(pk=project_id)
    todolist = ToDoList.objects.filter(project=project).get(pk=pk)

    if request.user != project.owner and request.user not in project.collaborators.all():
        messages.error(request, "You do not have permission to delete this To-Do List.")

        return redirect('project:project_detail', pk=project_id)

    if request.user == todolist.created_by or request.user == project.owner:
        todolist.delete()
        messages.success(request, 'ToDo list deleted successfully')

        return redirect('project:project_detail', pk=project_id)

    messages.error(request, "You do not have permission to delete this To-Do List.")

    return redirect('project:project_detail', pk=project_id)

todolist/templates/todolist/edit.html
{% extends 'core/base.html' %}
{% block title %}Add ToDo{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit ToDo</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action="{% url 'todolist:edit' project.id todolist.id %}">
        {% csrf_token %}
        <div>
            <label for="name" class="block mb-2 font-medium text-gray-900 dark:text-white">Name</label>
            <input type="text" id="name" name="name" value="{{ todolist.name }}" class="block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        </div>
        <div>
            <label for="description" class="block mb-2 font-medium text-gray-900 dark:text-white">Description</label>
            <textarea id="description" name="description" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">{{ todolist.description }}</textarea>
        </div>
        <div>
            <button class="py-4 px-8 bg-sky-600 text-white rounded-lg">Submit</button>
            <a href="{% url 'todolist:todolist' project.id todolist.id %}" class="py-4 px-8 bg-red-600 text-white rounded-lg">Cancel</a>
        </div>
    </form>

{% endblock %}