core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add_project, name='add'),
    path('<uuid:pk>/', views.project_detail, name='project_detail'),
    path('<uuid:pk>/edit/', views.edit_project, name='edit_project'),
    path('<uuid:pk>/delete_project/', views.delete_project, name='delete_project'),
    path('<uuid:project_id>/upload_file/', views.upload_file, name='upload_file'),
    path('<uuid:project_id>/<uuid:file_id>/delete_file/', views.delete_file, name='delete_file'),
    path('<uuid:project_id>/add_note/', views.add_note, name='add_note'),
    path('project/<uuid:project_id>/invite/', views.invite_collaborator, name='invite_collaborator'),
]

project_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from project_manager import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
import uuid
from django.db import models
from account.models import User


class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_projects')
    collaborators = models.ManyToManyField(User, through='ProjectCollaborator', related_name='collaborating_projects')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name


class ProjectCollaborator(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    role = models.CharField(max_length=255, blank=True, null=True, default='Collaborator')
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'project')

    def __str__(self):
        return f"{self.user.email} - {self.project.name}"


class ProjectFile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    attachment = models.FileField(upload_to='project_files')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='files')
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uploaded_files')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Notes(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    body = models.TextField(blank=True, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='notes')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_notes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Notes"

    def __str__(self):
        return self.title

project/forms.py
from django import forms
from django.forms import ModelForm
from .models import Project, ProjectFile, ProjectCollaborator


class ProjectFileForm(ModelForm):
    class Meta:
        model = ProjectFile
        fields = ['name', 'attachment']


class InviteCollaboratorForm(ModelForm):
    email = forms.EmailField()
    # role = forms.CharField(max_length=255, required=False)

    class Meta:
        model = ProjectCollaborator
        fields = ['email', 'role']

project/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from account.models import User
from .forms import ProjectFileForm, InviteCollaboratorForm
from .models import Project, ProjectFile, Notes, ProjectCollaborator


@login_required
def projects(request):
    user = request.user
    owned_projects = Project.objects.filter(owner=user)
    collaborated_projects = Project.objects.filter(collaborators=user)
    all_projects = (owned_projects | collaborated_projects).distinct().order_by('-created_at')

    return render(request, 'project/projects.html', {'projects': all_projects})


@login_required()
def add_project(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            project = Project.objects.create(name=name, description=description, owner=request.user)
            project.save()

            messages.success(request, 'Project created successfully')

            return redirect('project:projects')
        else:
            messages.error(request, 'Project name is required')

    return render(request, 'project/create_project.html')


@login_required()
def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    collaborators = ProjectCollaborator.objects.filter(project=project)
    project_files = ProjectFile.objects.filter(project=project).order_by('-uploaded_at')

    if request.user == project.owner or request.user in project.collaborators.all():
        return render(request, 'project/project_detail.html',
                      {'project': project, 'collaborators': collaborators, 'project_files': project_files})
    else:
        messages.error(request, "You do not have permission to access this project.")
        return redirect('projects')


@login_required()
def edit_project(request, pk):
    project = get_object_or_404(Project, pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            if request.user == project.owner:
                project.name = name
                project.description = description
                project.save()

                messages.success(request, 'Project updated successfully')

                return redirect('project:project_detail', pk=project.id)
            else:
                messages.error(request, 'You are not authorized to edit this project')
        else:
            messages.error(request, 'Project name is required')

    return redirect('project:project_detail', pk=project.id)


@login_required()
def delete_project(request, pk):
    project = get_object_or_404(Project, pk=pk)

    if request.user != project.owner:
        messages.error(request, 'You are not authorized to delete this project')

        return redirect('project:projects')

    project.delete()
    messages.success(request, 'Project deleted successfully')

    return redirect('project:projects')


@login_required
def upload_file(request, project_id):
    project = get_object_or_404(Project, pk=project_id)

    form = ProjectFileForm(request.POST, request.FILES)

    if request.method == 'POST':
        if request.user == project.owner or request.user in project.collaborators.all():

            if form.is_valid():
                file = form.save(commit=False)
                file.project = project
                file.uploaded_by = request.user

                file.save()

                messages.success(request, 'File uploaded successfully')
        else:
            messages.error(request, 'You are not authorized to upload files to this project')

    return redirect('project:project_detail', pk=project.id)


@login_required
def delete_file(request, project_id, file_id):
    project = get_object_or_404(Project, pk=project_id)

    file = get_object_or_404(ProjectFile, pk=file_id)

    if request.user != file.uploaded_by and request.user != project.owner:
        messages.error(request, 'You are not authorized to delete this file')

        return redirect('project:project_detail', pk=project.id)

    file.attachment.delete()
    file.delete()

    messages.success(request, 'File deleted successfully')

    return redirect('project:project_detail', pk=project.id)


@login_required()
def add_note(request, project_id):
    project = get_object_or_404(Project, pk=project_id)

    if request.method == 'POST':
        title = request.POST.get('title')
        body = request.POST.get('body')

        if request.user != project.owner and request.user not in project.collaborators.all():
            messages.error(request, "You do not have permission to add notes to this project.")
            return redirect('project:project_detail', pk=project.id)

        if title and body:
            note = Notes.objects.create(title=title, body=body, project=project, created_by=request.user)
            note.save()

            messages.success(request, 'Note added successfully')

            return redirect('project:project_detail', pk=project.id)

    return redirect('project:project_detail', pk=project.id)


@login_required
def invite_collaborator(request, project_id):
    project = get_object_or_404(Project, pk=project_id)

    if request.user != project.owner:
        messages.error(request, "You do not have permission to invite collaborators to this project.")
        return redirect('project:project_detail', project_id=project.id)

    if request.method == 'POST':
        form = InviteCollaboratorForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            role = form.cleaned_data['role'] or 'Collaborator'
            try:
                user = User.objects.get(email=email)
                if ProjectCollaborator.objects.filter(user=user, project=project).exists():
                    messages.warning(request, "This user is already a collaborator on this project.")
                else:
                    ProjectCollaborator.objects.create(user=user, project=project, role=role)
                    messages.success(request, f"{user.email} has been successfully invited as a collaborator.")
                    return redirect('project:project_detail', pk=project.id)
            except User.DoesNotExist:
                messages.error(request, "User not found.")
                return redirect('project:project_detail', pk=project.id)
    else:
        form = InviteCollaboratorForm()

    return redirect('project:project_detail', pk=project_id, form=form)

project/templates/project/create_project.html
{% extends 'core/base.html' %}
{% block title %}Add project{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add project</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action="{% url 'project:add' %}">
        {% csrf_token %}
        <div>
            <label for="name" class="block mb-2 font-medium text-gray-900 dark:text-white">Name</label>
            <input type="text" id="name" name="name" class="block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        </div>
        <div>
            <label for="description" class="block mb-2 font-medium text-gray-900 dark:text-white">Description</label>
            <textarea id="description" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white rounded-lg">Submit</button>
        </div>
    </form>

{% endblock %}

project/templates/project/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <div class="container">
        <div class="kanban-heading">
            <strong class="kanban-heading-text">Kanban Board</strong>
        </div>
        <div class="kanban-board">
            <div class="kanban-block" id="todo" ondrop="drop(event)" ondragover="allowDrop(event)">
                <strong>To Do</strong>
                <div class="task-button-block">
                    <button id="task-button" onclick="createTask()">Create new task</button>
                </div>
                {% for todolist in todolists %}
                    {% if todolist.status == 'open' %}
                        <div class="task" id="{{ todolist.id }}" draggable="true" ondragstart="drag(event)">
                            <span>{{ todolist.name }}</span>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="kanban-block" id="inprogress" ondrop="drop(event)" ondragover="allowDrop(event)">
                <strong>In Progress</strong>
                {% for todolist in todolists %}
                    {% if todolist.status == 'in_progress' %}
                        <div class="task" id="{{ todolist.id }}" draggable="true" ondragstart="drag(event)">
                            <span>{{ todolist.name }}</span>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="kanban-block" id="done" ondrop="drop(event)" ondragover="allowDrop(event)">
                <strong>Done</strong>
                {% for todolist in todolists %}
                    {% if todolist.status == 'done' %}
                        <div class="task" id="{{ todolist.id }}" draggable="true" ondragstart="drag(event)">
                            <span>{{ todolist.name }}</span>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="create-new-task-block" id="create-new-task-block">
                <strong>New Task</strong>
                <span class="form-row">
                    <label class="form-row-label" for="name">Task</label>
                    <input class="form-row-input" type="text" name="name" id="name">
                </span>
                <span class="form-row">
                    <label class="form-row-label" for="description">Description</label>
                    <textarea class="form-row-input" name="task-description" id="description" cols="70"
                              rows="10"></textarea>
                </span>
                <span class="form-row">
                    <label class="form-row-label" for="task-name">Status</label>
                    <select class="form-row-input" name="task-status" id="status">
                        <option value="todo">To Do</option>
                        <option value="inprogress">In Progress</option>
                        <option value="done">Done</option>
                    </select>
                </span>
                <span class="form-row-buttons">
                    <button id="edit-button" onclick="editTask()">Edit</button>
                    <button id="save-button" onclick="saveTask()">Save</button>
                    <button id="cancel-button" onclick="createTask()">Cancel</button>
                </span>
            </div>
        </div>
    </div>
    <script>
        let projectId = "{{ project.id }}";  // Assuming you have access to the project object in your template
    </script>

{% endblock %}

project/templates/project/edit_project.html
{% extends 'core/base.html' %}
{% block title %}Edit project{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit project</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action="{% url 'project:edit_project' project.id %}">
        {% csrf_token %}
        <div>
            <label for="name" class="block mb-2 font-medium text-gray-900 dark:text-white">Name</label>
            <input type="text" id="name" name="name" value="{{ project.name }}" class="block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        </div>
        <div>
            <label for="description" class="block mb-2 font-medium text-gray-900 dark:text-white">Description</label>
            <textarea id="description" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">{{ project.description }}</textarea>
        </div>
        <div>
            <button class="py-4 px-8 bg-sky-600 text-white rounded-lg">Submit</button>
            <a href="{% url 'project:project_detail' project.id %}" class="py-4 px-8 bg-red-600 text-white rounded-lg">Cancel</a>
        </div>
    </form>

{% endblock %}

project/templates/project/projects.html
{% extends 'core/base.html' %}
{% block title %}Projects{% endblock %}

{% block content %}

    <h1 class="mb-6 text-3xl">Projects</h1>
    <div class="mb-8 flex justify-start">
        <button data-modal-target="crud-modal" data-modal-toggle="crud-modal"
                class="block text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                type="button">
            Add Project
        </button>
        <!-- Main modal -->
        <div id="crud-modal" tabindex="-1" aria-hidden="true"
             class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
            <div class="relative p-4 w-full max-w-md max-h-full">
                <!-- Modal content -->
                <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                    <!-- Modal header -->
                    <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                            Add new Project
                        </h3>
                        <button type="button"
                                class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                                data-modal-toggle="crud-modal">
                            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                                 viewBox="0 0 14 14">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                      stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                            </svg>
                            <span class="sr-only">Close modal</span>
                        </button>
                    </div>
                    <!-- Modal body -->
                    <form class="p-4 md:p-5" method="post" action="{% url 'project:add' %}">
                        {% csrf_token %}
                        <div class="grid gap-4 mb-4 grid-cols-2">
                            <div class="col-span-2">
                                <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                    Name
                                </label>
                                <input type="text" name="name" id="name"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                            </div>
                            <div class="col-span-2">
                                <label for="description"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                    Description
                                </label>
                                <textarea id="description" rows="4" name="description" placeholder="Write description here"
                                          class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"></textarea>
                            </div>
                        </div>
                        <button type="submit"
                                class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            Save
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% if projects %}
        <div class="mt-6 mb-4 md:mb-8 lg:mb-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 lg:mb-2">
            {% for project in projects %}
                <div class="shadow-md divide-y divide-blue-200 block rounded-lg bg-gray-100 text-center text-surface shadow-secondary-1 dark:bg-surface-dark dark:text-white">
                    <div class="border-neutral-300 mx-2 px-6 py-3 dark:border-white/30">
                        Project
                    </div>
                    <div class="p-6">
                        <h5 class="mb-2 text-xl font-medium leading-tight ">
                            {{ project.name }}
                        </h5>
                        <p class="mb-4 text-sm ">
                            Todolists: {{ project.todolists.count }}
                        </p>
                        <p class="mb-4 text-sm ">
                            Files: {{ project.files.count }}
                        </p>
                        <p class="mb-4 text-sm ">
                            Collaborators: {{ project.collaborators.count }}
                        </p>
                        <a href="{% url 'project:project_detail' project.id %}"
                           type="button"
                           class="inline-block rounded bg-gradient-to-r from-cyan-500 to-blue-500 px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-primary-3 transition duration-150 ease-in-out hover:bg-primary-accent-300 hover:shadow-primary-2 focus:bg-primary-accent-300 focus:shadow-primary-2 focus:outline-none focus:ring-0 active:bg-primary-600 active:shadow-primary-2 dark:shadow-black/30 dark:hover:shadow-dark-strong dark:focus:shadow-dark-strong dark:active:shadow-dark-strong"
                           data-twe-ripple-init
                           data-twe-ripple-color="light">
                            Details
                        </a>
                    </div>
                    <div class="flex items-center justify-between border-t-2 border-neutral-300 mx-2 px-6 py-3 text-sm text-surface/75 dark:border-white/10 dark:text-neutral-300">
                        <div>
                            Owner: {% firstof project.owner.name project.owner.email %}
                        </div>
                        <div>
                            Added on: {{ project.created_at | date:"F j, Y" }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No projects found.</p>
    {% endif %}
{% endblock %}

project/templates/project/upload_file.html
{% extends 'core/base.html' %}
{% block title %}Project details{% endblock %}

{% block content %}
    <form action="{% url 'project:upload_file' project.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {#        {{ form.as_p }}#}
        <div class="flex items-center justify-center w-full">
            <label for="dropzone"
                   class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
                <div class="flex flex-col items-center justify-center pt-5 pb-6">
                    <svg class="w-8 h-8 mb-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"></path>
                    </svg>
                    <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span
                            class="font-semibold">Click to upload</span> or drag and drop</p>
                </div>
                <input id="dropzone" type="file" name="attachment" class="hidden"/>
            </label>
        </div>
        <span class="block flex gap-4 w-full rounded-md mt-4">
            <button type="submit"
                    class="flex justify-center py-2 px-4 border border-transparent font-medium rounded-md text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-blue-700 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
                  Upload
            </button>
            <a href="{% url 'project:project_detail' project.id %}"
                    class="flex justify-center py-2 px-4 border border-transparent font-medium rounded-md text-white bg-slate-500 hover:bg-slate-700 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
                  Cancel
            </a>
        </span>
    </form>
{% endblock %}